FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY scripts/db_utils.py scripts/
ARG SCRIPT
COPY ${SCRIPT} .
ENV SCRIPT=${SCRIPT}
ENV PYTHONUNBUFFERED=1
CMD python ${SCRIPT}
